name: "Cloud One Conformity Pipeline Scanner"
description: "Scan CloudFormation files with Cloud One Conformity."
inputs:
  CC_API_KEY:
    description: "Cloud One Conformity API Key"
    required: true
branding:
  icon: "check"
  color: "red"
runs:
  using: "nodejs"
  main: "scan.js"
  env:
    CC_API_KEY: ${{ inputs.CC_API_KEY }}
    CFN_TEMPLATE_FILE_LOCATION: ${{ inputs.CFN_TEMPLATE_FILE_LOCATION }}
    CC_REGION: ${{ inputs.CC_REGION }}
    CC_RISK_LEVEL: ${{ inputs.CC_RISK_LEVEL }}
