# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Conformity Template Scanner Pipeline
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: apt install nodejs
    - run: apt install npm
    - run: apt update -y
    - run: nvm install 12
    - run: npm version
    - run: npm install
    - run: npm test
    - name: Cloud One Conformity Pipeline Scanner
      uses: raphabot/conformity-template-scanner-pipeline@v1
      with:
        apikey: ${{ secrets.apikey }}
        region: us-west-2
        acceptedQty: 1
        template: s3.template.yaml
    - run: echo "Works!"
